// The event engine (plan section 2, "Layer 3: the event engine"): cards drawn under a pacing
// target, authored events that outrank them, and the world's type-wide category actions.

export {
  PREDICATE_ON,
  PREDICATE_OPS,
  EVENT_HOOK_OPS,
  EVENT_SIZES,
  FARM_DECK,
  loadDeck,
  momentKindOf,
  sizeOf,
  type Predicate,
  type PredicateOn,
  type PredicateOp,
  type CardWeight,
  type CardLimits,
  type EventHook,
  type EventHookOp,
  type EventSize,
  type EventHooks,
  type EventStorybook,
  type EventMoment,
  type Card,
  type AuthoredTrigger,
  type DeferredTrigger,
  type AuthoredEvent,
  type Deck,
  type DeckEntry,
} from './deck';
export {
  ENGINE_SEED_SALT,
  MOOD_RANGE,
  createEvents,
  cloneEvents,
  isRunning,
  runningCount,
  type EventsState,
  type RunningEvent,
  type LostLamb,
} from './events';
export {
  PACING,
  PACE_TARGETS,
  REFERENCE_WEIGHT,
  SIZE_PACING,
  SIM_MINUTES_PER_DAY,
  FARM_HOURS_PER_DAY,
  SIM_MINUTES_PER_FARM_HOUR,
  WARMUP_SIM_MINUTES,
  SMALL_GAP_SIM_MINUTES,
  BIG_GAP_SIM_MINUTES,
  UNWATCHED_LOOK_SIM_MINUTES,
  NO_REPEAT_SIM_MINUTES,
  farmHoursToSimMinutes,
  farmDaysToSimMinutes,
  simMinuteMs,
  simMinutesToMs,
  simHoursToMs,
  simDaysToMs,
  msToSimMinutes,
  drawChance,
} from './pacing';
export {
  PREDICATE_RULES,
  NEVER_RAINED_SIM_MINUTES,
  viewOf,
  readPredicate,
  compare,
  holds,
  allHold,
  lambAnchor,
  lambDistance,
  type EventView,
} from './view';
export { REFERENCE_RULES, REFERENCE_EFFECTS, findLostLamb, releaseLostLamb, runHook, runHooks, type ReferenceEffects } from './hooks';
export {
  CATEGORY_ACTIONS,
  SCHEDULED_CATEGORY_ACTIONS,
  MARKET_VISIT_K,
  growWool,
  marketVisitKey,
  runScheduledCategoryActions,
  sheepGrowWool,
  farmerMarketWalk,
  type CategoryAction,
  type PerActorCategoryAction,
  type ScheduledCategoryAction,
} from './category';
export {
  PARAMETER_COVERAGE,
  applyAuthoredIntent,
  attemptDraw,
  dayOfSeason,
  drawAllowed,
  eligibleCards,
  endEvent,
  evaluate,
  lastDrawOfSize,
  lastDrawOfSizeIn,
  liveWeight,
  pacingNow,
  preemptedByAuthored,
  readyAuthored,
  runningMoments,
  seasonDayOfFraction,
  seasonFraction,
  startEvent,
  tickEngine,
  triggerMet,
  type EligibleCard,
  type PacingNow,
} from './engine';
