"""Hand-drawn pixel grids. Every pixel placed on purpose. Light from top-left, 1px outline, soft interior shading."""
from PIL import Image

PAL = {
    ".": None,
    "k": (43, 29, 23),     # outline
    # sheep
    "w": (250, 246, 238),  # wool
    "h": (255, 255, 255),  # wool highlight
    "s": (220, 212, 198),  # wool shadow
    "f": (58, 52, 62),     # face / legs
    "g": (86, 79, 92),     # face highlight
    "e": (250, 246, 238),  # eye white
    "p": (236, 160, 176),  # pink (nose, inner ear, tongue)
    # digital luna
    "d": (94, 64, 48),     # coat base
    "b": (68, 44, 32),     # coat shadow (sel-out)
    "m": (124, 90, 68),    # coat highlight
    "c": (236, 226, 206),  # cream chest / beard
    "t": (206, 176, 138),  # tan muzzle
    "u": (216, 206, 186),  # cream shadow
    "n": (28, 18, 14),     # nose / pupil
}

SHEEP = """
......................kkkk......
....................kkhhhhkk....
...........kkkkk...khhhhhhhhk...
.........kkhhhhhkkkkhwwwwwwhk...
.......kkhhhhhhhhhkkkkkkkkkkk...
......khhhhhhhwwwwwkgggffffffk..
.....khhsshwwwwwwwwkggfffffffk..
....khhshwswwwwwwwwkgfffffffffk.
....khhhwwwwwwwsswkpkfeeefeeekpk
...khhhwwwwwwwswwskkkfeekfeekkkk
...khhwwwwwwwwwwwwwwkfffffffffk.
...khwwsswwwwwwwwwwwkffpppppfk..
...kwwswwswwwwwwwwwwkfffppfffk..
...kwwwwwwwwwsswwwwwwkfffffffk..
...kswwwwwwwswwswwwwwwkfffffk...
...ksswwwwwwwwwwwwwwwwwkkkkk....
....ssswwwwwwwwwwwwwwwwk........
....kssswwwwwwwwwwwwwwwk........
.....kssssswwwwwwwwwwwwk........
.....kssssssssswwwwwwwwk........
......kssssssssssssssswk........
.......kkffkkffkkkkffkkffk......
........kffkkffk..kffkkffk......
........kffkkffk..kffkkffk......
........kffkkffk..kffkkffk......
........kffkkffk..kffkkffk......
........kkkkkkkk..kkkkkkkk......
"""

def sheep_img():
    return to_img(SHEEP)

LUNA = """
............kkkkkkkk............
..........kkmmmdddddkk..........
.........kmmmdddddddddk.........
........kmmddddddddddddk........
.......kmdddddddddddddddk.......
......kmddddddddddddddddk.......
.....kkdddddddddddddddddkk......
....mmdkddddddddddddddddkddm....
...kmddkddddddddddddddddkddmk...
...kmddbdkkkkddddddkkkkdbddmk...
...kdddbkwwwwkddddkwwwwkbdddk...
...kddddkwhnwkddddkwhnwkdbddk...
...kddddkwnnwkddddkwnnwkdbddk...
...kdddddkkkkddddddkkkkddbddk...
...kdddbddddddddddddddddbbddk...
...kdddbddddddkcccckddddbdddk...
...kbddbdddddkccttttckdddbddk...
...kbddbddddkcttnnnttckddbddk...
....kbdbddddkcttttttckdddbdk....
....kbkbddddkkcctttckkddkbk.....
....kkk.kbddddkkckkckdddkkk.....
.........kbddddkkppkkdddk.......
..........kbdddkkppkkkdk........
...........kkbdkkkkkkkkk........
.........kkkkddkkcccccck........
........kdddddkcccccccccck......
.......kddddddkcccccccccck......
.....kkkddddddkuccccccccck......
....kwwkddddddkuccccccccck......
...khwwwkdddddkuccccccccck......
...khwwwkkddddkcuccucccucck.....
..khwwwwkkkdddkcuckcccckcck.....
..kwdddwwwwkkkkcucckcccckck.....
..kddddbwwwwwwkuccckcccckck.....
..kwddbwwwwwwwwuccckcccckck.....
..kswbwwwwwwwwwucccckccckck.....
...kssswwwwwwwwkcccckcccckk.....
....kksssswwwwkkuuuucuuuuck.....
......kkkkkkkkkkkkkkkkkkkkk.....
"""

def to_img(grid):
    rows = [r for r in grid.strip("\n").split("\n")]
    w = max(len(r) for r in rows); h = len(rows)
    im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    for y, r in enumerate(rows):
        for x, ch in enumerate(r.ljust(w, ".")):
            c = PAL[ch]
            if c: im.putpixel((x, y), c + (255,))
    return im

if __name__ == "__main__":
    import os
    from PIL import ImageDraw
    BUILD = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build"); os.makedirs(BUILD, exist_ok=True)
    S = 8
    sheep, luna = sheep_img(), to_img(LUNA)
    W = (sheep.width + luna.width + 12) * S
    out = Image.new("RGB", (W, 44 * S), (106, 170, 90))
    d = ImageDraw.Draw(out)
    for y in range(0, out.height, 3 * S):
        for x in range(0, out.width, 3 * S):
            if ((x + y) // (3 * S)) % 2: d.rectangle([x, y, x + 3 * S - 1, y + 3 * S - 1], fill=(98, 160, 84))
    out.paste(sheep.resize((sheep.width * S, sheep.height * S), Image.NEAREST), (4 * S, (44 - sheep.height) * S - 2 * S), sheep.resize((sheep.width * S, sheep.height * S), Image.NEAREST))
    out.paste(luna.resize((luna.width * S, luna.height * S), Image.NEAREST), ((sheep.width + 8) * S, (44 - luna.height) * S - 2 * S), luna.resize((luna.width * S, luna.height * S), Image.NEAREST))
    out.save(os.path.join(BUILD, "check_grid.png"))
    # true scale x3
    small = Image.new("RGB", ((sheep.width + luna.width + 12) * 3, 44 * 3), (106, 170, 90))
    small.paste(sheep.resize((sheep.width * 3, sheep.height * 3), Image.NEAREST), (12, (44 - sheep.height) * 3 - 6), sheep.resize((sheep.width * 3, sheep.height * 3), Image.NEAREST))
    small.paste(luna.resize((luna.width * 3, luna.height * 3), Image.NEAREST), ((sheep.width + 8) * 3, (44 - luna.height) * 3 - 6), luna.resize((luna.width * 3, luna.height * 3), Image.NEAREST))
    small.save(os.path.join(BUILD, "check_grid_small.png"))
    print(sheep.size, luna.size)
