// @sheepcliff/sim — pure TypeScript simulation core.
// No DOM, no timers, no Math.random. See docs/SHEEPCLIFF_PLAN.md section 5.

export const SIM_PACKAGE = '@sheepcliff/sim';

export { RULES, TICK_MS, TICK_SEC, type Rules } from './rules';
export { createRng, cloneRng, nextU32, nextFloat, nextRange, nextInt, chance, pick, type Rng } from './rng';
export {
  W,
  H,
  C,
  RX,
  RY,
  BARN,
  SPOT,
  POSTS,
  FLOWERS,
  SHEEP_SIZE,
  LUNA_SIZE,
  NPC_SIZE,
  SFOOT,
  LFOOT,
  inBarn,
  insideField,
  randomFoot,
  randomDir,
  type Point,
} from './geometry';
export {
  SEASONS,
  SEASON_TEMP,
  SEASON_ODDS,
  DEFAULT_REAL_EPOCH_MS,
  MS_PER_REAL_DAY,
  REAL_YEAR_MS,
  createClock,
  createSeason,
  phaseOf,
  advanceClock,
  advanceSeason,
  realMsOf,
  realMsAtSim,
  seasonSpanOf,
  seasonAtOffset,
  seasonFractionOf,
  seasonLengthOf,
  currentSeason,
  type Clock,
  type Phase,
  type Season,
  type SeasonName,
  type SeasonSpan,
  type CivilDate,
} from './clock';
export {
  civilFromDays,
  daysFromCivil,
  lastRealDateOccurrence,
  realDateAt,
  realDateMatches,
  realMsOfCivil,
  seasonAtRealMs,
  seasonFractionAtRealMs,
  seasonSpanAt,
  seasonStartDriftMs,
  seasonStartRealMs,
} from './calendar';
export { createWeather, setWeather, tickWeather, tempTarget, type Weather, type WeatherKind, type WeatherMode } from './weather';
export {
  SAVE_VERSION,
  NAMES,
  COLORS,
  createInitialState,
  cloneState,
  makeTufts,
  makeSheep,
  makeLuna,
  sheepFoot,
  lunaFoot,
  type SimState,
  type InitialStateOptions,
  type ActorId,
  type Dir,
  type Tuft,
  type Lamb,
  type Sheep,
  type Luna,
  type StickThrow,
  type Npc,
  type NpcJob,
  type Npcs,
  type Banks,
  type Settlement,
  type Life,
  type Rabbit,
  type Bird,
  type Butterfly,
  type Fly,
  type Stamper,
  type SnowPrint,
  type MudPatch,
  type Ground,
} from './state';
export {
  applyIntent,
  applyDueIntents,
  INTENT_TYPES,
  AUTHORED_ACTIONS,
  LUNA_ACTIONS,
  FARM_ACTIONS,
  SHEEP_ACTIONS,
  DEITY_WEATHER_KINDS,
  ACT_VERBS,
  type Intent,
  type IntentType,
  type LunaAction,
  type FarmAction,
  type SheepAction,
  type SheepTarget,
  type PetTarget,
  type DeityWeatherKind,
  type ActVerb,
  type ActCmd,
  type AuthoredAction,
} from './intents';
export { createRegistry, DEFAULT_CHAIN, type Behaviour, type Registry } from './behaviours/registry';
export {
  LUNA_BEHAVIOURS,
  IDLE_PLAYS,
  tickLuna,
  lunaContext,
  walkLuna,
  dismount,
  leaveBarn,
  petLuna,
  type LunaContext,
  type LunaBehaviour,
} from './behaviours/luna';
export {
  SHEEP_BEHAVIOURS,
  NEEDS,
  tickSheep,
  sheepContext,
  setPath,
  nextLeg,
  flockCount,
  newLamb,
  type SheepContext,
  type SheepBehaviour,
} from './behaviours/sheep';
export { NPC_FOOT, makeNpc, summonFarmer, summonMerchant, npcStep, tickNpcs, sellWoolAtMarket, type JobHook, type JobResult } from './npcs';
export { stepToward, clampField, clampTarget, clampMoverTarget, segHitsBarn, waypointAround, type Mover } from './movement';
export { LUNA_ID, findSheep, bubble, nearestTuft } from './actors';
export { tickRabbit, tickButterflies, tickBird, landBird } from './life';
export { groundSnowy, stampGround, tickGround, PRINT_CAP, MUD_CAP, MELT_MUD_CAP, STAMP_EVERY_PX, MUD_FADE_MS, MUD_FADE_RAIN_MS } from './ground';
export { tick, tickInPlace, advance } from './tick';
export { step, type StepOptions } from './step';
export { hashState, hashValue, canonicalJson, fnv1a, mix32 } from './hash';
export { SAVE_FORMAT, SaveError, type SaveDoc, type SaveWorld, type SaveErrorCode, type UnknownSaveDoc } from './save/doc';
export { toSave, fromSave, toSaveText, fromSaveText, validateWorld, findUnserializable, type LoadOptions } from './save/serialize';
export {
  MIGRATIONS,
  DEFAULT_MIGRATION_CONTEXT,
  migrateSave,
  assertMigrationChain,
  readVersion,
  type Migration,
  type MigrationContext,
} from './save/migrations/index';
export {
  LEDGER_STEP_MS,
  dayMs,
  meanOf,
  moodOf,
  summarise,
  cloneLedger,
  ledgerFlock,
  advanceLedger,
  GRAZE_SHARE,
  WALK_IN_MS,
  WALK_OUT_MS,
  respawn,
  diffLedger,
  catchUp,
  advanceUnwatched,
  type Ledger,
  type LedgerLamb,
  type LedgerDiff,
  type LedgerChange,
  type CatchUp,
  type CatchUpMode,
  type CatchUpOptions,
  type UnwatchedDraw,
  type UnwatchedRun,
} from './ledger/index';
export {
  FARM_DISTRICT,
  CHRONICLE_SOURCES,
  NOTABILITY_WINDOW,
  notabilityScale,
  deviationNotability,
  noteFact,
  createChronicleStats,
  cloneChronicleStats,
  createChronicle,
  cloneChronicle,
  tell,
  chronicleBetween,
  tellLedgerDiff,
  type ChronicleSource,
  type FactValue,
  type ChronicleEntry,
  type TellInput,
  type FactStat,
  type ChronicleStats,
  type Chronicle,
} from './chronicle/index';
export {
  PREDICATE_ON,
  PREDICATE_OPS,
  EVENT_HOOK_OPS,
  FARM_DECK,
  loadDeck,
  momentKindOf,
  sizeOf,
  EVENT_SIZES,
  ENGINE_SEED_SALT,
  MOOD_RANGE,
  createEvents,
  cloneEvents,
  isRunning,
  runningCount,
  PACING,
  PACE_TARGETS,
  REFERENCE_WEIGHT,
  SIZE_PACING,
  SIM_MINUTES_PER_DAY,
  FARM_HOURS_PER_DAY,
  SIM_MINUTES_PER_FARM_HOUR,
  WARMUP_SIM_MINUTES,
  SMALL_GAP_SIM_MINUTES,
  BIG_GAP_SIM_MINUTES,
  UNWATCHED_LOOK_SIM_MINUTES,
  NO_REPEAT_SIM_MINUTES,
  farmHoursToSimMinutes,
  farmDaysToSimMinutes,
  simMinuteMs,
  simMinutesToMs,
  simHoursToMs,
  simDaysToMs,
  msToSimMinutes,
  drawChance,
  PREDICATE_RULES,
  NEVER_RAINED_SIM_MINUTES,
  viewOf,
  readPredicate,
  compare,
  holds,
  allHold,
  lambAnchor,
  lambDistance,
  REFERENCE_RULES,
  REFERENCE_EFFECTS,
  findLostLamb,
  releaseLostLamb,
  runHook,
  runHooks,
  CATEGORY_ACTIONS,
  SCHEDULED_CATEGORY_ACTIONS,
  MARKET_VISIT_K,
  growWool,
  marketVisitKey,
  runScheduledCategoryActions,
  sheepGrowWool,
  farmerMarketWalk,
  PARAMETER_COVERAGE,
  applyAuthoredIntent,
  attemptDraw,
  dayOfSeason,
  drawAllowed,
  eligibleCards,
  endEvent,
  evaluate,
  lastDrawOfSize,
  lastDrawOfSizeIn,
  liveWeight,
  pacingNow,
  preemptedByAuthored,
  readyAuthored,
  realDateDue,
  runningMoments,
  seasonDayOfFraction,
  seasonFraction,
  startEvent,
  tickEngine,
  triggerMet,
  type Predicate,
  type PredicateOn,
  type PredicateOp,
  type CardWeight,
  type CardLimits,
  type EventHook,
  type EventHookOp,
  type EventHooks,
  type EventStorybook,
  type EventMoment,
  type Card,
  type AuthoredTrigger,
  type AuthoredEvent,
  type Deck,
  type DeckEntry,
  type EventsState,
  type RunningEvent,
  type LostLamb,
  type EventSize,
  type EventView,
  type ReferenceEffects,
  type CategoryAction,
  type PerActorCategoryAction,
  type ScheduledCategoryAction,
  type EligibleCard,
  type PacingNow,
} from './engine/index';
export { FETCH_LAMB_REACH_PX, fetchLamb } from './behaviours/luna';
export { summonFarmerToMarket } from './npcs';
